# This is a basic workflow to help you get started with Actions

name: MJ_CI/DE

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@master
    
    - name: Cache node_modules
      uses: actions/cache@v1
      with:
        path: node_modules
        key: ${{runner.OS}}-build-${{hashFiles('**/yarn.lock')}}
        restore-keys: |
          ${{ runner.OS }}-build-${{ runner.OS }}-
          
    - name: Install dependencies
      run: yarn install --pure-lockfile

    - name: Copy build to docs
      run: yarn run deploy
